files:
  - source: /app/src/main/res/values/strings.xml
    translation: /%original_path%-%two_letters_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        ur-PK: ur-rPK
        zh-TW: zh-rTW
        pt-PT: pt-rPT
        pt-BR: pt-rBR
        zh-CN: zh-rCN
